image: registry.gitlab.com/etermax/android/android-ci/java_11:latest

variables:
  AWS_ROLE_ARN: arn:aws:iam::804549073939:role/GitlabDeployX3Mediator

stages:
  - Checks & Build
  - Internal (Etermax)
  - External (X3M)

workflow:
  rules:
    - if: '$CI_COMMIT_TAG != null' 
      when: never
    - when: always

# Caches
.cache_gradle_wrapper_read_only: &cache_gradle_wrapper_read_only
  key: pbm-gradle-wrapper
  paths:
    - .gradle/wrapper
  policy: pull

.cache_gradle_caches_read_only: &cache_gradle_caches_read_only
  key: pbm-gradle-caches
  paths:
    - .gradle/caches
  policy: pull

.cache_all_write: &cache_all_write
  - <<: *cache_gradle_wrapper_read_only
    policy: pull-push
  - <<: *cache_gradle_caches_read_only
    policy: pull-push

.gradle_job:
  tags:
    - sre-runner
  before_script:
    - source ./ci/setup_gradle
  cache:
    - *cache_gradle_wrapper_read_only
    - *cache_gradle_caches_read_only

.publish_script: &publish_script
  - ./gradlew clean publish${PUBLICATION}PublicationToMavenRepository -PisSnapshot=$IS_SNAPSHOT -PisExternal=$IS_EXTERNAL -PuseLocalDependencies=false

.publish_internal:
  stage: Internal (Etermax)
  extends: .gradle_job
  script:
    - source ./ci/login_acceso_d
    - *publish_script
   # - source ./ci/setup_git
   # - source ./ci/tag_publication
  variables:
    IS_SNAPSHOT: "false"
    IS_EXTERNAL: "false"
  when: manual

.publish_external:
  stage: External (X3M)
  extends: .gradle_job
  script:
    - source ./ci/login_aws
    - *publish_script
  variables:
    IS_SNAPSHOT: "false"
    IS_EXTERNAL: "true"
  when: manual

Run Unit Tests:
  stage: Checks & Build
  extends: .gradle_job
  cache: *cache_all_write
  script:
    - ./gradlew :PrebidMobile-core:test
  except:
    - tags
  artifacts:
    reports:
      junit: ./*/build/test-results/**/TEST-*.xml

Publish Core Internal:
  extends: .publish_internal
  variables:
    PUBLICATION: PrebidMobileCore

Publish Core External:
  extends: .publish_external
  variables:
    PUBLICATION: PrebidMobileCore


