#!/bin/bash

git config --global user.name 'XAds CI'
git config --global user.email 'xads@etermax.com'
git remote set-url origin "https://$GITLAB_CI_WRITE_CREDENTIALS@gitlab.com/etermax/ads/xmediator/android.git"

