#!/bin/bash

function read_gradle_property {
   prop_value=$(cat "build.gradle" | grep "prebidSdkVersionName" | cut -d'=' -f2 | cut -d'"' -f2)
   echo "$prop_value"
}

version="$(read_gradle_property)"
tag="${version}"
branch_name="patch/${version}"

echo "Tag: ${tag}"
git tag "${tag}"
echo "Creating patch branch: ${branch_name}"
git branch "${branch_name}"
git push --tags --quiet
git push origin "${branch_name}" --quiet